name: Monthly Data Update

on:
  schedule:
    - cron: '0 2 1 * *'       # 1st of every month at 02:00 UTC
  workflow_dispatch:         # allows manual trigger

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run forecast script
        run: python update_data.py

      - name: Commit & push updated JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data_combined.json
          git commit -m "chore: monthly data update"
          git push
